namespace Core.Model;

public enum ESubscriptionState
{
    INITIALIZED,
    PERSONAL_DATA_ADDED,
    BILLING_ADDRESS_ADDED,
    PAYMENT_APPROVAL_PENDING,
    PAYMENT_APPROVED,
    PAYMENT_FAILURE,
    ACTIVATION_REQUESTED,
    ACTIVE,
    ACTIVATION_ERROR,
    SUSPENSION_REQUESTED,
    SUSPENDED,
    CANCEL_REQUESTED,
    CANCELED,
    EXPIRED,
    ABANDONED
}