version: '3.9'
services:
  # Keycloak para autorização
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    networks:
      - mesh-network
    restart: always

  # APIs da solução
  catalog-api:
    image: catalog-api:latest
    ports:
      - "5001:80"
    environment:
      - AUTH_URL=http://keycloak:8080/auth
      - CLIENT_ID=catalog-api
    networks:
      - mesh-network
    restart: always
  
  checkout-api:
    image: checkout-api:latest
    ports:
      - "5002:80"
    environment:
      - AUTH_URL=http://keycloak:8080/auth
      - CLIENT_ID=checkout-api
    networks:
      - mesh-network
    restart: always
  
  backoffice-api:
    image: backoffice-api:latest
    ports:
      - "5003:80"
    environment:
      - AUTH_URL=http://keycloak:8080/auth
      - CLIENT_ID=backoffice-api
    networks:
      - mesh-network
    restart: always
  
  customer-api:
    image: customer-api:latest
    ports:
      - "5004:80"
    environment:
      - AUTH_URL=http://keycloak:8080/auth
      - CLIENT_ID=customer-api
    networks:
      - mesh-network
    restart: always

  invoicing-api:
    image: invoicing-api:latest
    ports:
      - "5005:80"
    environment:
      - AUTH_URL=http://keycloak:8080/auth
      - CLIENT_ID=invoicing-api
    networks:
      - mesh-network
    restart: always

  notifications-api:
    image: notifications-api:latest
    ports:
      - "5006:80"
    environment:
      - AUTH_URL=http://keycloak:8080/auth
      - CLIENT_ID=notifications-api
    networks:
      - mesh-network
    restart: always
  
  subscriptions-api:
    image: subscriptions-api:latest
    ports:
      - "5007:80"
    environment:
      - AUTH_URL=http://keycloak:8080/auth
      - CLIENT_ID=subscriptions-api
    networks:
      - mesh-network
    restart: always

  webhook-api:
    image: webhook-api:latest
    ports:
      - "5008:80"
    environment:
      - AUTH_URL=http://keycloak:8080/auth
      - CLIENT_ID=webhook-api
    networks:
      - mesh-network
    restart: always

networks:
  mesh-network:
    driver: bridge
